server:
  port: 8017

spring:
  datasource:
#                         sqlsever的配置
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=AIS20231109104652
#    username: sa
#    password: Aa1216390501
#
#    jpa:
#      open-in-view: false

    url: jdbc:oracle:thin:@//36.138.132.30:1521/dbms
#    url: jdbc:oracle:thin:@//db.00.forestpacking.com:1522/dbms
    username: read
    password: ejsh.read
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
  mybatis-plus:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.example.webapp.entity
    global-config:
      db-config:
        id-type: auto
        logic-delete-value: 1
        logic-not-delete-value: 0
    configuration:
      map-underscore-to-camel-case: true
#  jpa:
#    hibernate:
#      ddl-auto: update #  意思我在项目中加了一个字段，数据库会自动增加一个相应的字段
logging:
  level:
    root: info # 从环境取
    com.test.demo: info
  file:
    name: logs/demo-server.log
  logback:
    rollingpolicy:
      max-file-size: 2MB
      file-name-pattern: logs/demo-server.%d{yyyy-MM-dd}.%i.log


kingdee:

  acctId: 66bc19b17df4ca
  username: Administrator
  password: slbz.2024

  lcid: 2052
  serverurl: http://localhost//k3cloud/
