server:
  port: 8017

spring:
  datasource:
#    primary:
#      url: jdbc:oracle:thin:@//36.138.132.30:1521/dbms?currentSchema=FERP
#      username: read
#      password: ejsh.read
#      driver-class-name: oracle.jdbc.OracleDriver
#      hikari:
#        minimum-idle: 5
#        maximum-pool-size: 15
#    secondary:
#      url: jdbc:oracle:thin:@//36.134.103.106:1521/dbms?currentSchema=FERP
#      username: read
#      password: ejsh.read
#      driver-class-name: oracle.jdbc.OracleDriver
#      hikari:
#        minimum-idle: 5
#        maximum-pool-size: 15
    url: jdbc:oracle:thin:@//36.138.132.30:1521/dbms?currentSchema=FERP
    username: read
    password: ejsh.read
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
  mybatis-plus:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.example.webapp.entity
    global-config:
      db-config:
        id-type: auto
        logic-delete-value: 1
        logic-not-delete-value: 0
    configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutLoggingImpl
#  jpa:
#    hibernate:
#      ddl-auto: update #  意思我在项目中加了一个字段，数据库会自动增加一个相应的字段
logging:
  level:
    root: info # 从环境取
    com.test.demo: info
    org.apache.ibatis: debug # 设置MyBatis相关的日志级别为debug，以便打印SQL语句
    com.baomidou.mybatis-plus: debug # 设置MyBatis-Plus相关的日志级别为debug，以便打印SQL语句
  file:
    name: logs/demo-server.log
  logback:
    rollingpolicy:
      max-file-size: 2MB
      file-name-pattern: logs/demo-server.%d{yyyy-MM-dd}.%i.log


kingdee:

#  acctId: 66f52f3013f11b
#  username: Administrator
#  password: KINGDEE@123

  acctId: 66bc19b17df4ca
  username: Administrator
  password: slbz.2024
  lcid: 2052
  serverurl: http://localhost//k3cloud/
